-- AlterTable
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "leanBodyMassKg" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "heightCm" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "distanceKm" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "flightsClimbed" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "restingEnergyKcal" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "activeEnergyKcal" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "walkingSpeedKmh" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "walkingStepLengthCm" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "walkingAsymmetryPercent" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "doubleSupportPercent" DOUBLE PRECISION;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "walkingSteadiness" TEXT;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "headphoneLevel" TEXT;
ALTER TABLE "HealthDay" ADD COLUMN IF NOT EXISTS "sleepScore" DOUBLE PRECISION;
